#!/bin/bash
#
# Checks the added lines in the to-be-committed diff for swear words, and
# aborts the commit if any is found.

HOOK_ROOT="$(dirname $0)/.."
if [[ ! -d "${HOOK_ROOT}" ]]
then
    # Script might be running via a symlink...
    REAL_ME=$(readlink -f $0)
    HOOK_ROOT="$(dirname ${REAL_ME})/.."
fi

if [[ ! -d "${HOOK_ROOT}" ]]
then
    echo "No proper root found next to hook - bogus setup?" >&2
    exit 1
fi

${HOOK_ROOT}/usr/libexec/pos-diff-grepper \
    "${HOOK_ROOT}/usr/share/swearwords.txt" \
    diff-cached \
    1 \
    "Preventing commit due to swearing."
